# Generated by Django 5.1.1 on 2024-12-15 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='portfolio_api_app.portfolio'),
        ),
        migrations.CreateModel(
            name='WorkExperince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('years', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='portfolio_api_app.portfolio')),
            ],
        ),
    ]
