# Generated by Django 5.1.1 on 2024-12-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api_app', '0003_remove_customuser_portfolio_alter_portfolio_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperince',
            old_name='job_seeker',
            new_name='user',
        ),
    ]
