# Generated by Django 5.1.1 on 2024-12-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api_app', '0004_rename_job_seeker_workexperince_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperince',
            old_name='years',
            new_name='date',
        ),
    ]
