# Generated by Django 5.1.1 on 2024-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api_app', '0006_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
    ]
