# Generated by Django 5.1.1 on 2024-12-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api_app', '0007_language_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='user',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='workexperince',
            old_name='user',
            new_name='portfolio',
        ),
    ]
