# Generated by Django 5.1.1 on 2024-12-18 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api_app', '0008_rename_user_language_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperince',
            name='tags',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='portfolio_api_app.workexperince')),
            ],
        ),
    ]
