# Generated by Django 5.1.1 on 2024-12-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api_app', '0009_remove_workexperince_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='work_experience',
        ),
    ]
